"""empty message

Revision ID: 3969c30d891e
Revises: 6b09d6da5a1e
Create Date: 2021-01-20 13:20:43.597313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3969c30d891e'
down_revision = '6b09d6da5a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'upcomin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('upcomin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
