"""empty message

Revision ID: 557a9298b280
Revises: 2269b749cabe
Create Date: 2021-01-19 22:07:42.823239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557a9298b280'
down_revision = '2269b749cabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
