"""empty message

Revision ID: e79f6f10388e
Revises: ecb652e7bacb
Create Date: 2021-01-18 21:52:23.151134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79f6f10388e'
down_revision = 'ecb652e7bacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
