"""empty message

Revision ID: ecb652e7bacb
Revises: 1c1e8b077af6
Create Date: 2021-01-18 21:49:36.415548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb652e7bacb'
down_revision = '1c1e8b077af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist_Genre',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.add_column('Artist', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Artist', 'Location', ['location_id'], ['id'])
    op.execute('UPDATE "Artist" set location_id=1 where location_id is null')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'location_id')
    op.drop_table('Artist_Genre')
    # ### end Alembic commands ###
